/**
 * ASTRA v2.9 — TS ↔ NumPy active-inference equivalence test
 * Asserts the production TypeScript ActiveInferenceCore reproduces the
 * verified NumPy reference (python/second_order/active_inference_loop.py)
 * bit-for-bit (within 1e-9) on a fixed observation sequence. The golden
 * fixture is regenerated by `npm run golden` and checked in CI by
 * `npm run golden:check`.
 *
 * © 2026 Christophe Jean Legros — Geneva
 */

import { test, describe } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { ActiveInferenceCore } from '../src/engine/tcai/active-inference.js';

const here = dirname(fileURLToPath(import.meta.url));
const golden = JSON.parse(readFileSync(join(here, 'fixtures', 'aif_golden.json'), 'utf8')) as {
  config: { numObs: number; numStates: number; numControls: number; gamma: number; lr: number };
  C: number[];
  sequence: number[];
  steps: Array<{
    obs: number; freeEnergy: number; expectedFreeEnergy: number[];
    pragmatic: number; epistemic: number; action: number;
  }>;
};

const TOL = 1e-9;

describe('ActiveInference · TS ↔ NumPy equivalence (golden)', () => {
  test('TypeScript core reproduces the NumPy reference within 1e-9', () => {
    const { numObs, numStates, numControls, gamma, lr } = golden.config;
    const aif = new ActiveInferenceCore(numObs, numStates, numControls, gamma, lr);

    for (let i = 0; i < golden.sequence.length; i++) {
      const r = aif.step(golden.sequence[i], golden.C);
      const g = golden.steps[i];
      assert.ok(Math.abs(r.freeEnergy - g.freeEnergy) < TOL,
        `step ${i} F: TS ${r.freeEnergy} vs NumPy ${g.freeEnergy}`);
      assert.ok(Math.abs(r.pragmatic - g.pragmatic) < TOL,
        `step ${i} pragmatic: TS ${r.pragmatic} vs NumPy ${g.pragmatic}`);
      assert.ok(Math.abs(r.epistemic - g.epistemic) < TOL,
        `step ${i} epistemic: TS ${r.epistemic} vs NumPy ${g.epistemic}`);
      assert.equal(r.action, g.action, `step ${i} action mismatch`);
      assert.equal(r.expectedFreeEnergy.length, g.expectedFreeEnergy.length);
      for (let u = 0; u < g.expectedFreeEnergy.length; u++) {
        assert.ok(Math.abs(r.expectedFreeEnergy[u] - g.expectedFreeEnergy[u]) < TOL,
          `step ${i} G[${u}]: TS ${r.expectedFreeEnergy[u]} vs NumPy ${g.expectedFreeEnergy[u]}`);
      }
    }
  });
});
